version: "3.7"
services:
  db:
    image: postgres:12.1-alpine
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_dev
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=db
      - MIX_ENV=dev
      - SECRET_KEY_BASE=dunnome
    depends_on:
      - db
volumes:
  postgres_data: null
